# Entry points configuration
entryPoints:
  DockerNodeNetwork:
    address: ":80"
  websecure:
    address: ":443"

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.skybox.localhost`)"
    network: DockerNodeNetwork  # Important for container communication

# API and dashboard configuration
api:
  insecure: true
  dashboard: true